name: "Basic CI / CD Pipeline"
on:
  push:
    branches: ["main"]
#jobs section
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: "Checkout repository"
        uses: actions/checkout@v4
      # Step 2: Set up Node.js environment
      - name: "Set up Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Step 3: Install dependencies
      - name: "Install dependencies"
        run: npm install
      # Step 4: Run tests
      - name: "Run tests"
        run: npm test
      # Step 5: Build the project
      - name: "Build project"
        run: npm run build
      # Step 6: Deploy to VPS
      - name: "Deploy to VPS"
        env:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
        secrets: |
          cd /var/www/myapp || exit 1
          git pull origin main
          npm install
          npm run build
          pm2 restart all
