name: "Basic CI / CD Pipeline"
on:
  push:
    branches: ["main"]
#jobs section
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: "Checkout repository"
