name: CI Pipeline
on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
      # Step 4: Lint the code
      - name: Lint code
        run: npm run lint
      # Step 4: Run tests
      - name: Run tests
        run: npm test
      # Step 5: Build the project
      - name: Build project
        run: npm run build
