name: Docker CI/CD

jobs:
  lint-check:

  build-and-push:
    runs-on: ubuntu-latest
    # needs: lint-check
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY_NAME }}
          tags: |
            type=sha,prefix=,suffix=
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: api
          push: true
          tags: ${{ steps.meta.outputs.tags }} #0rf1az/mycoolwebapp:7ea9e4b
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4
      - name: Transfer docker compose file to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.DEPLOYMENT_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.INSTANCE_RSA_PRIVATE_KEY }}
          source: "docker-compose.production.yaml,nginx.conf"
          target: "~/"
      - name: Deploy mycoolwebapp using docker compose
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.DEPLOYMENT_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.INSTANCE_RSA_PRIVATE_KEY }}
          script: |
            export COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
            docker compose -f docker-compose.production.yaml up -d
