name: Cloudflare CDN deployment
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  cloudflare-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
      - name: Build
        run: npm install && npm run build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./build --project-name=todo-frontend --branch=master
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
