#Stage 1
FROM node:18-alpine AS builder
# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

#Stage 2
FROM node:18-alpine AS runner
# Set working directory
WORKDIR /app
# Copy only the necessary files from the builder stage
COPY --from=builder /app .
# Expose the port the app runs on
EXPOSE 3000
# Start the application
CMD ["npm", "start"]